# SUSY Les Houches Accord 2 - radinu/ZeeHB Spectrum + Decays + Flavor Observables
# SPheno module generated by SARAH
# ----------------------------------------------------------------------
# SPheno v3.3.8  
#   W. Porod, Comput. Phys. Commun. 153 (2003) 275-315, hep-ph/0301101
#   W. Porod, F.Staub, Comput.Phys.Commun.183 (2012) 2458-2469, arXiv:1104.1573
# SARAH: 4.9.1   
#   F. Staub; arXiv:0806.0538 (online manual)
#   F. Staub; Comput. Phys. Commun. 181 (2010) 1077-1086; arXiv:0909.2863
#   F. Staub; Comput. Phys. Commun. 182 (2011)  808-833; arXiv:1002.0840
#   F. Staub; Comput. Phys. Commun. 184 (2013)  1792-1809; arXiv:1207.0906
#   F. Staub; Comput. Phys. Commun. 185 (2014)  1773-1790; arXiv:1309.7223 
# Including the calculation of flavor observables based on the FlavorKit 
#   W. Porod, F. Staub, A. Vicente; Eur.Phys.J. C74 (2014) 8, 2992; arXiv:1405.1434 
# Two-loop masss corrections to Higgs fields based on 
#   M. D. Goodsell, K. Nickel, F. Staub; arXiv:1411.0675 
#   M. D. Goodsell, K. Nickel, F. Staub; arXiv:1503.03098
#  
# in case of problems send email to florian.staub@cern.ch and goodsell@lpthe.jussieu.fr 
# ----------------------------------------------------------------------
# Created: 06.04.2017,  11:46
Block SPINFO         # Program information
     1   SPhenoSARAH      # spectrum calculator
     2   v3.3.8      # version number of SPheno
     9   4.9.1       # version number of SARAH
Block MODSEL  # Input parameters
     1  1   #  GUT scale input
     2  1   #  Boundary conditions 
     6  1   #  switching on flavour violation
Block MINPAR  # Input parameters
    1    2.57733888E-01  # lambda1Input
    2    1.30000000E-01  # lambda2Input
    3    1.00000000E-03  # lambda3Input
    4   -1.14778503E+01  # lambda4Input
    5   -1.33196920E-01  # lambda5Input
    6    1.00000000E-03  # lambda6Input
    7    0.00000000E+00  # lambda7Input
    8    0.00000000E+00  # lambda8Input
    9    0.00000000E+00  # lambda9Input
   10    0.00000000E+00  # lambda10Input
   11    0.00000000E+00  # lambdahInput
   12    6.40017641E+05  # MhInput
   13    1.44740880E+01  # MuInput
   14    9.99952047E+05  # mEt2Input
Block gaugeGUT Q= -1.00000000E+00  # (GUT scale)
   1    0.00000000E+00  # g1(Q)^DRbar
   2    0.00000000E+00  # g2(Q)^DRbar
   3    0.00000000E+00  # g3(Q)^DRbar
Block SMINPUTS  # SM parameters
         2     1.16637000E-05  # G_mu [GeV^-2]
         3     1.18700000E-01  # alpha_s(MZ)^MSbar
         4     9.11887000E+01  # m_Z(pole)
         5     4.18000000E+00  # m_b(m_b), MSbar
         6     1.73500000E+02  # m_t(pole)
         7     1.77669000E+00  # m_tau(pole)
Block GAUGE Q=  1.60000000E+02  # (Renormalization Scale)
   1    3.55734740E-01  # g1
   2    6.62881508E-01  # g2
   3    1.22132231E+00  # g3
Block HDM Q=  1.60000000E+02  # (Renormalization Scale)
   2    2.57733888E-01  # lam1
   3    1.30000000E-01  # lam2
   5   -1.14778503E+01  # lam4
   4    1.00000000E-03  # lam3
   8    0.00000000E+00  # lam7
   6   -1.33196920E-01  # lam5
   7    1.00000000E-03  # lam6
  10    0.00000000E+00  # lam9
   9    0.00000000E+00  # lam8
  12    0.00000000E+00  # lamh
  11    0.00000000E+00  # lam10
  15    1.44740880E+01  # mu
   1    9.99952047E+05  # mEt2
  13    3.03122843E+01  # m12
  14    6.40017641E+05  # mh
Block SM Q=  1.60000000E+02  # (Renormalization Scale)
   3   -7.81250289E+03  # mH2
Block VV Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # vv
   1    0.00000000E+00  # vv
Block HMIX Q=  1.60000000E+02  # (Renormalization Scale)
   3    2.46220569E+02  # v
  11    1.57089219E+00  # alphaH
Block TREEHDM Q=  1.60000000E+02  # (Renormalization Scale)
  13    3.14140426E+01  # m12
Block TREESM Q=  1.60000000E+02  # (Renormalization Scale)
   3   -8.09646334E+03  # mH2
Block LOOPHDM Q=  1.60000000E+02  # (Renormalization Scale)
  13   -4.50197556E+02  # m12
Block LOOPSM Q=  1.60000000E+02  # (Renormalization Scale)
   3    1.47720182E+05  # mH2
Block epsU Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     0.00000000E+00   # Real(epsU(1,1),dp)
  1  2     0.00000000E+00   # Real(epsU(1,2),dp)
  1  3     0.00000000E+00   # Real(epsU(1,3),dp)
  2  1     0.00000000E+00   # Real(epsU(2,1),dp)
  2  2     0.00000000E+00   # Real(epsU(2,2),dp)
  2  3     0.00000000E+00   # Real(epsU(2,3),dp)
  3  1     0.00000000E+00   # Real(epsU(3,1),dp)
  3  2     0.00000000E+00   # Real(epsU(3,2),dp)
  3  3     9.96529469E-01   # Real(epsU(3,3),dp)
Block Yu Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     1.43592143E-05   # Real(Yu(1,1),dp)
  1  2     0.00000000E+00   # Real(Yu(1,2),dp)
  1  3     0.00000000E+00   # Real(Yu(1,3),dp)
  2  1     0.00000000E+00   # Real(Yu(2,1),dp)
  2  2     7.29448084E-03   # Real(Yu(2,2),dp)
  2  3     0.00000000E+00   # Real(Yu(2,3),dp)
  3  1     0.00000000E+00   # Real(Yu(3,1),dp)
  3  2     0.00000000E+00   # Real(Yu(3,2),dp)
  3  3     9.96529469E-01   # Real(Yu(3,3),dp)
Block epsD Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     0.00000000E+00   # Real(epsD(1,1),dp)
  1  2     0.00000000E+00   # Real(epsD(1,2),dp)
  1  3     0.00000000E+00   # Real(epsD(1,3),dp)
  2  1     0.00000000E+00   # Real(epsD(2,1),dp)
  2  2     0.00000000E+00   # Real(epsD(2,2),dp)
  2  3     0.00000000E+00   # Real(epsD(2,3),dp)
  3  1     0.00000000E+00   # Real(epsD(3,1),dp)
  3  2     0.00000000E+00   # Real(epsD(3,2),dp)
  3  3     2.40086062E-02   # Real(epsD(3,3),dp)
Block epsE Q=  1.60000000E+02  # (Renormalization Scale)
  1  1    -1.75383398E-01   # Real(epsE(1,1),dp)
  1  2     1.00000000E-03   # Real(epsE(1,2),dp)
  1  3     1.00000000E-06   # Real(epsE(1,3),dp)
  2  1     2.00000000E-01   # Real(epsE(2,1),dp)
  2  2    -1.02121663E-03   # Real(epsE(2,2),dp)
  2  3     0.00000000E+00   # Real(epsE(2,3),dp)
  3  1     5.57391109E-03   # Real(epsE(3,1),dp)
  3  2    -1.00000000E-05   # Real(epsE(3,2),dp)
  3  3     0.00000000E+00   # Real(epsE(3,3),dp)
Block Yd Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     2.87184285E-05   # Real(Yd(1,1),dp)
  1  2     0.00000000E+00   # Real(Yd(1,2),dp)
  1  3     0.00000000E+00   # Real(Yd(1,3),dp)
  2  1     0.00000000E+00   # Real(Yd(2,1),dp)
  2  2     5.45650142E-04   # Real(Yd(2,2),dp)
  2  3     0.00000000E+00   # Real(Yd(2,3),dp)
  3  1     0.00000000E+00   # Real(Yd(3,1),dp)
  3  2     0.00000000E+00   # Real(Yd(3,2),dp)
  3  3     2.40086062E-02   # Real(Yd(3,3),dp)
Block Ye Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     2.93501725E-06   # Real(Ye(1,1),dp)
  1  2     0.00000000E+00   # Real(Ye(1,2),dp)
  1  3     0.00000000E+00   # Real(Ye(1,3),dp)
  2  1     0.00000000E+00   # Real(Ye(2,1),dp)
  2  2     6.06868478E-04   # Real(Ye(2,2),dp)
  2  3     0.00000000E+00   # Real(Ye(2,3),dp)
  3  1     0.00000000E+00   # Real(Ye(3,1),dp)
  3  2     0.00000000E+00   # Real(Ye(3,2),dp)
  3  3     1.02047490E-02   # Real(Ye(3,3),dp)
Block Yh Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     0.00000000E+00   # Real(Yh(1,1),dp)
  1  2     2.01598341E-03   # Real(Yh(1,2),dp)
  1  3     1.29282502E-01   # Real(Yh(1,3),dp)
  2  1    -2.01598341E-03   # Real(Yh(2,1),dp)
  2  2     0.00000000E+00   # Real(Yh(2,2),dp)
  2  3     1.15483710E-01   # Real(Yh(2,3),dp)
  3  1    -1.29282502E-01   # Real(Yh(3,1),dp)
  3  2    -1.15483710E-01   # Real(Yh(3,2),dp)
  3  3     0.00000000E+00   # Real(Yh(3,3),dp)
Block MASS  # Mass spectrum
#   PDG code      mass          particle
        25     1.25000000E+02  # hh_1
        35     8.05000000E+02  # hh_2
        37     8.00000000E+02  # Hm_2
    900037     1.00000000E+03  # Hm_3
        36     8.10000000E+02  # etI
        23     9.11887000E+01  # VZ
        24     8.03497269E+01  # VWp
         1     5.00000000E-03  # Fd_1
         3     9.50000000E-02  # Fd_2
         5     4.18000000E+00  # Fd_3
         2     2.50000000E-03  # Fu_1
         4     1.27000000E+00  # Fu_2
         6     1.73500000E+02  # Fu_3
        11     5.10998930E-04  # Fe_1
        13     1.05658372E-01  # Fe_2
        15     1.77669000E+00  # Fe_3
        12     2.48890530E-16  # Fv_1
        14     5.11981986E-11  # Fv_2
        16    -5.19810036E-11  # Fv_3
Block SCALARMIX Q=  1.60000000E+02  # ()
  1  1     9.99999995E-01   # ZH(1,1)
  1  2    -9.58642771E-05   # ZH(1,2)
  2  1     9.58642771E-05   # ZH(2,1)
  2  2     9.99999995E-01   # ZH(2,2)
Block CHARGEMIX Q=  1.60000000E+02  # ()
  1  1     0.00000000E+00   # ZP(1,1)
  1  2     1.00000000E+00   # ZP(1,2)
  1  3     0.00000000E+00   # ZP(1,3)
  2  1     9.99975498E-01   # ZP(2,1)
  2  2     0.00000000E+00   # ZP(2,2)
  2  3     7.00017153E-03   # ZP(2,3)
  3  1    -7.00017153E-03   # ZP(3,1)
  3  2     0.00000000E+00   # ZP(3,2)
  3  3     9.99975498E-01   # ZP(3,3)
Block UVMIX Q=  1.60000000E+02  # ()
  1  1    -4.84418574E-01   # Real(UV(1,1),dp)
  1  2     7.18859477E-01   # Real(UV(1,2),dp)
  1  3    -4.98577674E-01   # Real(UV(1,3),dp)
  2  1     8.58817080E-01   # Real(UV(2,1),dp)
  2  2     2.82198572E-01   # Real(UV(2,2),dp)
  2  3    -4.27547880E-01   # Real(UV(2,3),dp)
  3  1     1.66648938E-01   # Real(UV(3,1),dp)
  3  2     6.35299157E-01   # Real(UV(3,2),dp)
  3  3     7.54071027E-01   # Real(UV(3,3),dp)
Block UDLMIX Q=  1.60000000E+02  # ()
  1  1    -1.00000000E+00   # Real(ZDL(1,1),dp)
  1  2     0.00000000E+00   # Real(ZDL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZDL(1,3),dp)
  2  1     0.00000000E+00   # Real(ZDL(2,1),dp)
  2  2    -1.00000000E+00   # Real(ZDL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZDL(2,3),dp)
  3  1     0.00000000E+00   # Real(ZDL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZDL(3,2),dp)
  3  3    -1.00000000E+00   # Real(ZDL(3,3),dp)
Block UDRMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZDR(1,1),dp)
  1  2     0.00000000E+00   # Real(ZDR(1,2),dp)
  1  3     0.00000000E+00   # Real(ZDR(1,3),dp)
  2  1     0.00000000E+00   # Real(ZDR(2,1),dp)
  2  2     1.00000000E+00   # Real(ZDR(2,2),dp)
  2  3     0.00000000E+00   # Real(ZDR(2,3),dp)
  3  1     0.00000000E+00   # Real(ZDR(3,1),dp)
  3  2     0.00000000E+00   # Real(ZDR(3,2),dp)
  3  3     1.00000000E+00   # Real(ZDR(3,3),dp)
Block UULMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZUL(1,1),dp)
  1  2     0.00000000E+00   # Real(ZUL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZUL(1,3),dp)
  2  1     0.00000000E+00   # Real(ZUL(2,1),dp)
  2  2     1.00000000E+00   # Real(ZUL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZUL(2,3),dp)
  3  1     0.00000000E+00   # Real(ZUL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZUL(3,2),dp)
  3  3     1.00000000E+00   # Real(ZUL(3,3),dp)
Block UURMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZUR(1,1),dp)
  1  2     0.00000000E+00   # Real(ZUR(1,2),dp)
  1  3     0.00000000E+00   # Real(ZUR(1,3),dp)
  2  1     0.00000000E+00   # Real(ZUR(2,1),dp)
  2  2     1.00000000E+00   # Real(ZUR(2,2),dp)
  2  3     0.00000000E+00   # Real(ZUR(2,3),dp)
  3  1     0.00000000E+00   # Real(ZUR(3,1),dp)
  3  2     0.00000000E+00   # Real(ZUR(3,2),dp)
  3  3     1.00000000E+00   # Real(ZUR(3,3),dp)
Block UELMIX Q=  1.60000000E+02  # ()
  1  1    -1.00000000E+00   # Real(ZEL(1,1),dp)
  1  2     0.00000000E+00   # Real(ZEL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZEL(1,3),dp)
  2  1     0.00000000E+00   # Real(ZEL(2,1),dp)
  2  2    -1.00000000E+00   # Real(ZEL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZEL(2,3),dp)
  3  1     0.00000000E+00   # Real(ZEL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZEL(3,2),dp)
  3  3    -1.00000000E+00   # Real(ZEL(3,3),dp)
Block UERMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZER(1,1),dp)
  1  2     0.00000000E+00   # Real(ZER(1,2),dp)
  1  3     0.00000000E+00   # Real(ZER(1,3),dp)
  2  1     0.00000000E+00   # Real(ZER(2,1),dp)
  2  2     1.00000000E+00   # Real(ZER(2,2),dp)
  2  3     0.00000000E+00   # Real(ZER(2,3),dp)
  3  1     0.00000000E+00   # Real(ZER(3,1),dp)
  3  2     0.00000000E+00   # Real(ZER(3,2),dp)
  3  3     1.00000000E+00   # Real(ZER(3,3),dp)
Block SPheno # SPheno internal parameters 
         1    -1.00000000E+00  # ErrorLevel
         2     0.00000000E+00  # SPA_conventions
        11     1.00000000E+00  # Branching ratios
        13     1.00000000E+00  # 3 Body decays
        31    -1.00000000E+00  # GUT scale
        33     1.60000000E+02  # Renormalization scale
        34     1.00000000E-04  # Precision
        35     4.00000000E+01  # Iterations
        38     2.00000000E+00  # RGE level
        40     7.29735257E-03  # Alpha
        41     2.49520000E+00  # Gamma_Z
        42     2.06000000E+00  # Gamma_W
        50     0.00000000E+00  # Rotate negative fermion masses
        51     0.00000000E+00  # Switch to SCKM matrix
        52     1.00000000E+00  # Ignore negative masses
        53     0.00000000E+00  # Ignore negative masses at MZ
        55     0.00000000E+00  # Calculate one loop masses
        56     1.00000000E+00  # Calculate two-loop Higgs masses
        57     1.00000000E+00  # Calculate low energy
        60     1.00000000E+00  # Include kinetic mixing
        65     1.00000000E+00  # Solution of tadpole equation
Block HiggsLHC7 # Higgs production cross section at LHC7 [pb] (rescaled SM values from HXSWG) 
  1        25        1.60529900E+01 # Gluon fusion 
  2        25        1.29940291E+00 # Vector boson fusion 
  3        25        5.82370947E-01 # W-H production 
  4        25        3.40051047E-01 # Z-H production 
  5        25        8.62540607E-02 # t-t-H production 
  1        35        6.48292059E-02 # Gluon fusion 
  2        35        3.68986914E-10 # Vector boson fusion 
Block HiggsLHC8 # Higgs production cross section at LHC8 [pb] (rescaled SM values from HXSWG) 
  1        25        2.04327483E+01 # Gluon fusion 
  2        25        1.67542743E+00 # Vector boson fusion 
  3        25        7.46562641E-01 # W-H production 
  4        25        4.24712893E-01 # Z-H production 
  5        25        1.30557304E-01 # t-t-H production 
  1        35        1.06175014E-01 # Gluon fusion 
  2        35        6.14831518E-10 # Vector boson fusion 
Block HiggsLHC13 # Higgs production cross section at LHC13 [pb] (rescaled SM values from SusHI 1.5.0) 
  1        25        4.77373815E+01 # Gluon fusion 
  1        35        4.42156004E-01 # Gluon fusion 
Block HiggsLHC14 # Higgs production cross section at LHC14 [pb] (rescaled SM values from SusHI 1.5.0)
  1        25        5.37566854E+01 # Gluon fusion 
  1        35        5.15077151E-01 # Gluon fusion 
Block HiggsFCC100 # Higgs production cross section at FCC-pp [pb] (rescaled SM values from SusHI 1.5.0)
  1        25        7.91646479E+02 # Gluon fusion 
  1        35        3.58004952E+01 # Gluon fusion 
Block HiggsBoundsInputHiggsCouplingsFermions # 
    4.56581846E-01    0.00000000E+00        3             25         5         5 # h_1 b b coupling 
    3.29293301E-01    0.00000000E+00        3             25         3         3 # h_1 s s coupling 
    1.00150694E+00    0.00000000E+00        3             25         6         6 # h_1 t t coupling  
    2.32836729E-01    0.00000000E+00        3             25         4         4 # h_1 c c coupling 
    9.97644702E-01    0.00000000E+00        3             25        15        15 # h_1 tau tau coupling 
    9.76417038E-01    0.00000000E+00        3             25        13        13 # h_1 mu mu coupling  
    1.00011501E+00    0.00000000E+00        3             35         5         5 # h_2 b b coupling 
    2.38466739E-09    0.00000000E+00        3             35         3         3 # h_2 s s coupling 
    9.98873707E-01    0.00000000E+00        3             35         6         6 # h_2 t t coupling  
    1.31395569E-09    0.00000000E+00        3             35         4         4 # h_2 c c coupling 
    9.26377637E-09    0.00000000E+00        3             35        15        15 # h_2 tau tau coupling 
    2.83137538E+00    0.00000000E+00        3             35        13        13 # h_2 mu mu coupling  
Block HiggsBoundsInputHiggsCouplingsBosons # 
    1.07591530E+00        3             25        24        24 # h_1 W W coupling 
    1.07466527E+00        3             25        23        23 # h_1 Z Z coupling  
    0.00000000E+00        3             25        23        22 # h_1 Z gamma coupling 
    1.08718657E+00        3             25        22        22 # h_1 gamma gamma coupling 
    1.04590360E+00        3             25        21        21 # h_1 g g coupling 
    0.00000000E+00        4             25        21        21        23 # h_1 g g Z coupling 
    1.02479419E-08        3             35        24        24 # h_2 W W coupling 
    1.02745533E-08        3             35        23        23 # h_2 Z Z coupling  
    0.00000000E+00        3             35        23        22 # h_2 Z gamma coupling 
    3.25458518E+00        3             35        22        22 # h_2 gamma gamma coupling 
    9.98663749E-01        3             35        21        21 # h_2 g g coupling 
    0.00000000E+00        4             35        21        21        23 # h_2 g g Z coupling 
    0.00000000E+00        3             25        25        23 # h_1 h_1 Z coupling  
    0.00000000E+00        3             25        35        23 # h_1 h_2 Z coupling  
    0.00000000E+00        3             35        25        23 # h_2 h_1 Z coupling  
    0.00000000E+00        3             35        35        23 # h_2 h_2 Z coupling  
Block EFFHIGGSCOUPLINGS # values of loop-induced couplings 
        25           22           22     0.32704918E-04 # H-Photon-Photon 
        25           21           21     0.66127636E-04 # H-Gluon-Gluon 
        25           22           23     0.00000000E+00 # H-Photon-Z (not yet calculated by SPheno) 
        35           22           22     0.92208367E-05 # H-Photon-Photon 
        35           21           21     0.55480234E-04 # H-Gluon-Gluon 
        35           22           23     0.00000000E+00 # H-Photon-Z (not yet calculated by SPheno) 
Block SPhenoLowEnergy # low energy observables 
      20    1.22596344E-16  # (g-2)_e
      21    1.39708088E-12  # (g-2)_mu
      22    9.80249837E-10  # (g-2)_tau
      23    0.00000000E+00  # EDM(e)
      24    0.00000000E+00  # EDM(mu)
      25    0.00000000E+00  # EDM(tau)
      39    5.44915395E-03  # delta(rho)
Block FlavorKitQFV # quark flavor violating observables 
     200    3.14768414E-04  # BR(B->X_s gamma)
     201    9.99264806E-01  # BR(B->X_s gamma)/BR(B->X_s gamma)_SM
     300    2.63375744E-03  # BR(D->mu nu)
     301    9.98906539E-01  # BR(D->mu nu)/BR(D->mu nu)_SM
     400    2.49253441E-02  # BR(Ds->mu nu)
     401    9.98787406E-01  # BR(Ds->mu nu)/BR(Ds->mu nu)_SM
     402    2.43597240E-01  # BR(Ds->tau nu)
     403    9.98787311E-01  # BR(Ds->tau nu)/BR(Ds->tau nu)_SM
     500    2.22757726E-06  # BR(B->mu nu)
     501    9.65031503E-01  # BR(B->mu nu)/BR(B->mu nu)_SM
     502    5.09131607E-04  # BR(B->tau nu)
     503    9.91250192E-01  # BR(B->tau nu)/BR(B->tau nu)_SM
     600    2.82849121E+00  # BR(K->mu nu)
     601    9.99923711E-01  # BR(K->mu nu)/BR(K->mu nu)_SM
     602    2.47647707E-05  # R_K = BR(K->e nu)/(K->mu nu)
     603    2.47609896E-05  # R_K^SM = BR(K->e nu)_SM/(K->mu nu)_SM
    1900    1.78630105E+01  # Delta(M_Bs)
    1901    1.00082206E+00  # Delta(M_Bs)/Delta(M_Bs)_SM
    1902    3.99321026E-01  # Delta(M_Bd)
    1903    1.00096598E+00  # Delta(M_Bd)/Delta(M_Bd)_SM
    4000    1.20546930E-14  # BR(B^0_d->e e)
    4001    4.86589190E+00  # BR(B^0_d->e e)/BR(B^0_d->e e)_SM
    4002    3.80653205E-13  # BR(B^0_s->e e)
    4003    4.94844215E+00  # BR(B^0_s->e e)/BR(B^0_s->e e)_SM
    4004    1.05886792E-10  # BR(B^0_d->mu mu)
    4005    1.00052578E+00  # BR(B^0_d->mu mu)/BR(B^0_d->mu mu)_SM
    4006    3.28793031E-09  # BR(B^0_s->mu mu)
    4007    1.00053106E+00  # BR(B^0_s->mu mu)/BR(B^0_s->mu mu)_SM
    4008    2.21628221E-08  # BR(B^0_d->tau tau)
    4009    1.00050100E+00  # BR(B^0_d->tau tau)/BR(B^0_d->tau tau)_SM
    4010    6.97287564E-07  # BR(B^0_s->tau tau)
    4011    1.00050141E+00  # BR(B^0_s->tau tau)/BR(B^0_s->tau tau)_SM
    5000    1.64203086E-06  # BR(B-> s e e)
    5001    9.91989837E-01  # BR(B-> s e e)/BR(B-> s e e)_SM
    5002    1.59160469E-06  # BR(B-> s mu mu)
    5003    9.91783778E-01  # BR(B-> s mu mu)/BR(B-> s mu mu)_SM
    6000    1.10228418E-07  # BR(B -> K mu mu)
    6001    9.93048811E-01  # BR(B -> K mu mu)/BR(B -> K mu mu)_SM
    7000    4.09990539E-05  # BR(B->s nu nu)
    7001    1.00032222E+00  # BR(B->s nu nu)/BR(B->s nu nu)_SM
    7002    1.89836749E-06  # BR(B->D nu nu)
    7003    1.00032198E+00  # BR(B->D nu nu)/BR(B->D nu nu)_SM
    8000    1.29975749E-10  # BR(K^+ -> pi^+ nu nu)
    8001    1.00000106E+00  # BR(K^+ -> pi^+ nu nu)/BR(K^+ -> pi^+ nu nu)_SM
    8002    3.02793568E-11  # BR(K_L -> pi^0 nu nu)
    8003    1.00000184E+00  # BR(K_L -> pi^0 nu nu)/BR(K_L -> pi^0 nu nu)_SM
    9100    1.94739313E-15  # Delta(M_K)
    9102    9.99999331E-01  # Delta(M_K)/Delta(M_K)_SM
    9103    1.84342659E-03  # epsilon_K
    9104    1.00000355E+00  # epsilon_K/epsilon_K^SM
Block FlavorKitLFV # lepton flavor violating observables 
     701    8.93446185E-10  # BR(mu->e gamma)
     702    9.13653977E-15  # BR(tau->e gamma)
     703    1.23439839E-14  # BR(tau->mu gamma)
     800    2.56641538E-09  # CR(mu-e, Al)
     801    4.61773037E-09  # CR(mu-e, Ti)
     802    6.25127026E-09  # CR(mu-e, Sr)
     803    7.02643527E-09  # CR(mu-e, Sb)
     804    3.78371772E-09  # CR(mu-e, Au)
     805    3.55876605E-09  # CR(mu-e, Pb)
     901    6.08779601E-07  # BR(mu->3e)
     902    8.36333399E-11  # BR(tau->3e)
     903    4.78750940E-14  # BR(tau->3mu)
     904    3.18044941E-14  # BR(tau- -> e- mu+ mu-)
     905    1.12840398E-10  # BR(tau- -> mu- e+ e-)
     906    3.78846876E-16  # BR(tau- -> e+ mu- mu-)
     907    1.50480061E-14  # BR(tau- -> mu+ e- e-)
    1001    8.70812719E-12  # BR(Z->e mu)
    1002    4.30995039E-16  # BR(Z->e tau)
    1003    5.24558687E-16  # BR(Z->mu tau)
    1101    1.46671059E-02  # BR(h->e mu)
    1102    1.15165592E-05  # BR(h->e tau)
    1103    3.60735473E-11  # BR(h->mu tau)
    2001    2.88119551E-21  # BR(tau->e pi)
    2002    4.26074574E-22  # BR(tau->e eta)
    2003    4.69949985E-22  # BR(tau->e eta')
    2004    3.69974510E-21  # BR(tau->mu pi)
    2005    5.46967168E-22  # BR(tau->mu eta)
    2006    5.98683284E-22  # BR(tau->mu eta')
Block FWCOEF Q=  1.60000000E+02  # Wilson coefficients at scale Q 
     0305 4422   00   0    -0.17242737E-08    # coeffC7sm
     0305 4422   00   2    -0.17222372E-08    # coeffC7
     0305 4322   00   2    -0.33128294E-10    # coeffC7p
     0305 4422   00   1     0.20364771E-11    # coeffC7NP
     0305 4322   00   1    -0.33128294E-10    # coeffC7pNP
     0305 6421   00   0    -0.86378433E-09    # coeffC8sm
     0305 6421   00   2    -0.86135413E-09    # coeffC8
     0305 6321   00   2    -0.16533938E-10    # coeffC8p
     0305 6421   00   1     0.24301974E-11    # coeffC8NP
     0305 6321   00   1    -0.16533938E-10    # coeffC8pNP
 03051111 4133   00   0     0.10360690E-08    # coeffC9eeSM
 03051111 4133   00   2     0.10361548E-08    # coeffC9ee
 03051111 4233   00   2    -0.80179926E-15    # coeffC9Pee
 03051111 4133   00   1     0.85715650E-13    # coeffC9eeNP
 03051111 4233   00   1    -0.80179926E-15    # coeffC9PeeNP
 03051111 4137   00   0    -0.39426686E-08    # coeffC10eeSM
 03051111 4137   00   2    -0.39436650E-08    # coeffC10ee
 03051111 4237   00   2    -0.80804867E-14    # coeffC10Pee
 03051111 4137   00   1    -0.99641634E-12    # coeffC10eeNP
 03051111 4237   00   1    -0.80804867E-14    # coeffC10PeeNP
 03051313 4133   00   0     0.10360685E-08    # coeffC9mumuSM
 03051313 4133   00   2     0.10361662E-08    # coeffC9mumu
 03051313 4233   00   2    -0.79931757E-15    # coeffC9Pmumu
 03051313 4133   00   1     0.97676256E-13    # coeffC9mumuNP
 03051313 4233   00   1    -0.79931757E-15    # coeffC9PmumuNP
 03051313 4137   00   0    -0.39426691E-08    # coeffC10mumuSM
 03051313 4137   00   2    -0.39436536E-08    # coeffC10mumu
 03051313 4237   00   2    -0.80811402E-14    # coeffC10Pmumu
 03051313 4137   00   1    -0.98445330E-12    # coeffC10mumuNP
 03051313 4237   00   1    -0.80811402E-14    # coeffC10PmumuNP
 03051212 4141   00   0    -0.12182258E-07    # coeffCLnu1nu1SM
 03051212 4141   00   2    -0.12184217E-07    # coeffCLnu1nu1
 03051212 4241   00   2     0.16162993E-13    # coeffCLPnu1nu1
 03051212 4141   00   1    -0.19587608E-11    # coeffCLnu1nu1NP
 03051212 4241   00   1     0.16162993E-13    # coeffCLPnu1nu1NP
 03051414 4141   00   0    -0.12182142E-07    # coeffCLnu2nu2SM
 03051414 4141   00   2    -0.12184098E-07    # coeffCLnu2nu2
 03051414 4241   00   2     0.16163049E-13    # coeffCLPnu2nu2
 03051414 4141   00   1    -0.19557252E-11    # coeffCLnu2nu2NP
 03051414 4241   00   1     0.16163049E-13    # coeffCLPnu2nu2NP
 03051616 4141   00   0    -0.12157348E-07    # coeffCLnu3nu3SM
 03051616 4141   00   2    -0.12159317E-07    # coeffCLnu3nu3
 03051616 4241   00   2     0.16158877E-13    # coeffCLPnu3nu3
 03051616 4141   00   1    -0.19690384E-11    # coeffCLnu3nu3NP
 03051616 4241   00   1     0.16158877E-13    # coeffCLPnu3nu3NP
 03051212 4142   00   0     0.00000000E+00    # coeffCRnu1nu1SM
 03051212 4142   00   2     0.12184217E-07    # coeffCRnu1nu1
 03051212 4242   00   2    -0.16162993E-13    # coeffCRPnu1nu1
 03051212 4142   00   1     0.12184217E-07    # coeffCRnu1nu1NP
 03051212 4242   00   1    -0.16162993E-13    # coeffCRPnu1nu1NP
 03051414 4142   00   0     0.00000000E+00    # coeffCRnu2nu2SM
 03051414 4142   00   2     0.12184107E-07    # coeffCRnu2nu2
 03051414 4242   00   2    -0.16163049E-13    # coeffCRPnu2nu2
 03051414 4142   00   1     0.12184107E-07    # coeffCRnu2nu2NP
 03051414 4242   00   1    -0.16163049E-13    # coeffCRPnu2nu2NP
 03051616 4142   00   0     0.00000000E+00    # coeffCRnu3nu3SM
 03051616 4142   00   2     0.12162078E-07    # coeffCRnu3nu3
 03051616 4242   00   2    -0.16158877E-13    # coeffCRPnu3nu3
 03051616 4142   00   1     0.12162078E-07    # coeffCRnu3nu3NP
 03051616 4242   00   1    -0.16158877E-13    # coeffCRPnu3nu3NP
 01030103 3131   00   2    -0.18585925E-23    # coeffKK_SLL
 01030103 3232   00   2    -0.67093991E-21    # coeffKK_SRR
 01030103 3132   00   2    -0.85722960E-20    # coeffKK_SLR
 01030103 4141   00   2     0.96965898E-13    # coeffKK_VLL
 01030103 4242   00   2     0.11950469E-28    # coeffKK_VRR
 01030103 4142   00   2    -0.35312948E-22    # coeffKK_VLR
 01030103 4343   00   2    -0.11962182E-31    # coeffKK_TLL
 01030103 4444   00   2     0.11200851E-30    # coeffKK_TRR
 01050105 3131   00   2    -0.54109455E-21    # coeffBB_SLL
 01050105 3232   00   2    -0.94994655E-15    # coeffBB_SRR
 01050105 3132   00   2    -0.76946964E-17    # coeffBB_SLR
 01050105 4141   00   2     0.33476235E-11    # coeffBB_VLL
 01050105 4242   00   2     0.76503360E-21    # coeffBB_VRR
 01050105 4142   00   2    -0.96425493E-18    # coeffBB_VLR
 01050105 4343   00   2    -0.11488028E-21    # coeffBB_TLL
 01050105 4444   00   2     0.14484408E-20    # coeffBB_TRR
 03050305 3131   00   2    -0.10214156E-16    # coeffBsBs_SLL
 03050305 3232   00   2    -0.27750932E-13    # coeffBsBs_SRR
 03050305 3132   00   2    -0.42720412E-14    # coeffBsBs_SLR
 03050305 4141   00   2     0.97808384E-10    # coeffBsBs_VLL
 03050305 4242   00   2    -0.33958825E-20    # coeffBsBs_VRR
 03050305 4142   00   2    -0.53513179E-15    # coeffBsBs_VLR
 03050305 4343   00   2    -0.23482271E-20    # coeffBsBs_TLL
 03050305 4444   00   2     0.47381256E-19    # coeffBsBs_TRR
 01030103 3131   00   1    -0.89791916E-29    # coeffKK_SLLNP
 01030103 3232   00   1    -0.34495748E-26    # coeffKK_SRRNP
 01030103 3132   00   1    -0.16110867E-26    # coeffKK_SLRNP
 01030103 4141   00   1     0.14535495E-19    # coeffKK_VLLNP
 01030103 4242   00   1    -0.77971953E-31    # coeffKK_VRRNP
 01030103 4142   00   1    -0.18208440E-27    # coeffKK_VLRNP
 01030103 4343   00   1    -0.11962182E-31    # coeffKK_TLLNP
 01030103 4444   00   1     0.11200851E-30    # coeffKK_TRRNP
 01050105 3131   00   1     0.43548318E-21    # coeffBB_SLLNP
 01050105 3232   00   1    -0.49651290E-18    # coeffBB_SRRNP
 01050105 3132   00   1     0.29631921E-20    # coeffBB_SLRNP
 01050105 4141   00   1     0.15875467E-14    # coeffBB_VLLNP
 01050105 4242   00   1     0.76474884E-21    # coeffBB_VRRNP
 01050105 4142   00   1    -0.13365728E-20    # coeffBB_VLRNP
 01050105 4343   00   1    -0.11488028E-21    # coeffBB_TLLNP
 01050105 4444   00   1     0.14484408E-20    # coeffBB_TRRNP
 03050305 3131   00   1     0.84618450E-19    # coeffBsBs_SLLNP
 03050305 3232   00   1    -0.14440600E-16    # coeffBsBs_SRRNP
 03050305 3132   00   1     0.18301367E-17    # coeffBsBs_SLRNP
 03050305 4141   00   1     0.46408631E-13    # coeffBsBs_VLLNP
 03050305 4242   00   1    -0.64006782E-20    # coeffBsBs_VRRNP
 03050305 4142   00   1    -0.66769483E-18    # coeffBsBs_VLRNP
 03050305 4343   00   1    -0.23482271E-20    # coeffBsBs_TLLNP
 03050305 4444   00   1     0.47381256E-19    # coeffBsBs_TRRNP
 01030103 3131   00   0    -0.18585835E-23    # coeffKK_SLLSM
 01030103 3232   00   0    -0.67093646E-21    # coeffKK_SRRSM
 01030103 3132   00   0    -0.85722944E-20    # coeffKK_SLRSM
 01030103 4141   00   0     0.96965883E-13    # coeffKK_VLLSM
 01030103 4242   00   0     0.12028441E-28    # coeffKK_VRRSM
 01030103 4142   00   0    -0.35312766E-22    # coeffKK_VLRSM
 01030103 4343   00   0    -0.12744148E-46    # coeffKK_TLLSM
 01030103 4444   00   0     0.54095175E-47    # coeffKK_TRRSM
 01050105 3131   00   0    -0.97657774E-21    # coeffBB_SLLSM
 01050105 3232   00   0    -0.94945004E-15    # coeffBB_SRRSM
 01050105 3132   00   0    -0.76976596E-17    # coeffBB_SLRSM
 01050105 4141   00   0     0.33460359E-11    # coeffBB_VLLSM
 01050105 4242   00   0     0.28475327E-24    # coeffBB_VRRSM
 01050105 4142   00   0    -0.96291836E-18    # coeffBB_VLRSM
 01050105 4343   00   0    -0.51131523E-53    # coeffBB_TLLSM
 01050105 4444   00   0    -0.69461968E-48    # coeffBB_TRRSM
 03050305 3131   00   0    -0.10298774E-16    # coeffBsBs_SLLSM
 03050305 3232   00   0    -0.27736492E-13    # coeffBsBs_SRRSM
 03050305 3132   00   0    -0.42738713E-14    # coeffBsBs_SLRSM
 03050305 4141   00   0     0.97761975E-10    # coeffBsBs_VLLSM
 03050305 4242   00   0     0.30047957E-20    # coeffBsBs_VRRSM
 03050305 4142   00   0    -0.53446409E-15    # coeffBsBs_VLRSM
 03050305 4343   00   0    -0.21673473E-49    # coeffBsBs_TLLSM
 03050305 4444   00   0    -0.34727931E-46    # coeffBsBs_TRRSM
Block IMFWCOEF Q=  1.60000000E+02  # Im(Wilson coefficients) at scale Q 
     0305 4422   00   0     0.64264752E-10    # coeffC7sm
     0305 4422   00   2     0.64301095E-10    # coeffC7
     0305 4322   00   2     0.23234024E-11    # coeffC7p
     0305 4422   00   1     0.36342687E-13    # coeffC7NP
     0305 4322   00   1     0.23234024E-11    # coeffC7pNP
     0305 6421   00   0     0.74444241E-10    # coeffC8sm
     0305 6421   00   2     0.74487610E-10    # coeffC8
     0305 6321   00   2     0.14364666E-11    # coeffC8p
     0305 6421   00   1     0.43368965E-13    # coeffC8NP
     0305 6321   00   1     0.14364666E-11    # coeffC8pNP
 03051111 4133   00   0    -0.18499673E-10    # coeffC9eeSM
 03051111 4133   00   2    -0.18501203E-10    # coeffC9ee
 03051111 4233   00   2     0.14321167E-16    # coeffC9Pee
 03051111 4133   00   1    -0.15296696E-14    # coeffC9eeNP
 03051111 4233   00   1     0.14321167E-16    # coeffC9PeeNP
 03051111 4137   00   0     0.70361763E-10    # coeffC10eeSM
 03051111 4137   00   2     0.70379545E-10    # coeffC10ee
 03051111 4237   00   2     0.14432799E-15    # coeffC10Pee
 03051111 4137   00   1     0.17781907E-13    # coeffC10eeNP
 03051111 4237   00   1     0.14432799E-15    # coeffC10PeeNP
 03051313 4133   00   0    -0.18499664E-10    # coeffC9mumuSM
 03051313 4133   00   2    -0.18501407E-10    # coeffC9mumu
 03051313 4233   00   2     0.14276879E-16    # coeffC9Pmumu
 03051313 4133   00   1    -0.17431169E-14    # coeffC9mumuNP
 03051313 4233   00   1     0.14276879E-16    # coeffC9PmumuNP
 03051313 4137   00   0     0.70361772E-10    # coeffC10mumuSM
 03051313 4137   00   2     0.70379340E-10    # coeffC10mumu
 03051313 4237   00   2     0.14433965E-15    # coeffC10Pmumu
 03051313 4137   00   1     0.17568417E-13    # coeffC10mumuNP
 03051313 4237   00   1     0.14433965E-15    # coeffC10PmumuNP
 03051212 4141   00   0     0.21747229E-09    # coeffCLnu1nu1SM
 03051212 4141   00   2     0.21750725E-09    # coeffCLnu1nu1
 03051212 4241   00   2    -0.28869202E-15    # coeffCLPnu1nu1
 03051212 4141   00   1     0.34955773E-13    # coeffCLnu1nu1NP
 03051212 4241   00   1    -0.28869202E-15    # coeffCLPnu1nu1NP
 03051414 4141   00   0     0.21746929E-09    # coeffCLnu2nu2SM
 03051414 4141   00   2     0.21750419E-09    # coeffCLnu2nu2
 03051414 4241   00   2    -0.28869302E-15    # coeffCLPnu2nu2
 03051414 4141   00   1     0.34901600E-13    # coeffCLnu2nu2NP
 03051414 4241   00   1    -0.28869302E-15    # coeffCLPnu2nu2NP
 03051616 4141   00   0     0.21700445E-09    # coeffCLnu3nu3SM
 03051616 4141   00   2     0.21703959E-09    # coeffCLnu3nu3
 03051616 4241   00   2    -0.28861851E-15    # coeffCLPnu3nu3
 03051616 4141   00   1     0.35139185E-13    # coeffCLnu3nu3NP
 03051616 4241   00   1    -0.28861851E-15    # coeffCLPnu3nu3NP
 03051212 4142   00   0     0.00000000E+00    # coeffCRnu1nu1SM
 03051212 4142   00   2    -0.21750725E-09    # coeffCRnu1nu1
 03051212 4242   00   2     0.28869202E-15    # coeffCRPnu1nu1
 03051212 4142   00   1    -0.21750725E-09    # coeffCRnu1nu1NP
 03051212 4242   00   1     0.28869202E-15    # coeffCRPnu1nu1NP
 03051414 4142   00   0     0.00000000E+00    # coeffCRnu2nu2SM
 03051414 4142   00   2    -0.21750436E-09    # coeffCRnu2nu2
 03051414 4242   00   2     0.28869302E-15    # coeffCRPnu2nu2
 03051414 4142   00   1    -0.21750436E-09    # coeffCRnu2nu2NP
 03051414 4242   00   1     0.28869302E-15    # coeffCRPnu2nu2NP
 03051616 4142   00   0     0.00000000E+00    # coeffCRnu3nu3SM
 03051616 4142   00   2    -0.21708890E-09    # coeffCRnu3nu3
 03051616 4242   00   2     0.28861851E-15    # coeffCRPnu3nu3
 03051616 4142   00   1    -0.21708890E-09    # coeffCRnu3nu3NP
 03051616 4242   00   1     0.28861851E-15    # coeffCRPnu3nu3NP
 01030103 3131   00   2    -0.16120452E-23    # coeffKK_SLL
 01030103 3232   00   2    -0.58193794E-21    # coeffKK_SRR
 01030103 3132   00   2    -0.31013355E-21    # coeffKK_SLR
 01030103 4141   00   2     0.61821400E-14    # coeffKK_VLL
 01030103 4242   00   2     0.19197557E-30    # coeffKK_VRR
 01030103 4142   00   2    -0.30628592E-22    # coeffKK_VLR
 01030103 4343   00   2    -0.11613112E-31    # coeffKK_TLL
 01030103 4444   00   2     0.10873997E-30    # coeffKK_TRR
 01050105 3131   00   2    -0.48913988E-21    # coeffBB_SLL
 01050105 3232   00   2    -0.85865306E-15    # coeffBB_SRR
 01050105 3132   00   2    -0.69597628E-17    # coeffBB_SLR
 01050105 4141   00   2     0.30267897E-11    # coeffBB_VLL
 01050105 4242   00   2     0.69142956E-21    # coeffBB_VRR
 01050105 4142   00   2    -0.87158629E-18    # coeffBB_VLR
 01050105 4343   00   2    -0.10382757E-21    # coeffBB_TLL
 01050105 4444   00   2     0.13090853E-20    # coeffBB_TRR
 03050305 3131   00   2     0.36470493E-18    # coeffBsBs_SLL
 03050305 3232   00   2     0.99086947E-15    # coeffBsBs_SRR
 03050305 3132   00   2     0.15260099E-15    # coeffBsBs_SLR
 03050305 4141   00   2    -0.34929854E-11    # coeffBsBs_VLL
 03050305 4242   00   2     0.12114487E-21    # coeffBsBs_VRR
 03050305 4142   00   2     0.19107312E-16    # coeffBsBs_VLR
 03050305 4343   00   2     0.83838969E-22    # coeffBsBs_TLL
 03050305 4444   00   2    -0.16916574E-20    # coeffBsBs_TRR
 01030103 3131   00   1    -0.87170537E-29    # coeffKK_SLLNP
 01030103 3232   00   1    -0.33489881E-26    # coeffKK_SRRNP
 01030103 3132   00   1    -0.15642808E-26    # coeffKK_SLRNP
 01030103 4141   00   1     0.14111200E-19    # coeffKK_VLLNP
 01030103 4242   00   1    -0.75696637E-31    # coeffKK_VRRNP
 01030103 4142   00   1    -0.17677191E-27    # coeffKK_VLRNP
 01030103 4343   00   1    -0.11613112E-31    # coeffKK_TLLNP
 01030103 4444   00   1     0.10873997E-30    # coeffKK_TRRNP
 01050105 3131   00   1     0.39358506E-21    # coeffBB_SLLNP
 01050105 3232   00   1    -0.44875379E-18    # coeffBB_SRRNP
 01050105 3132   00   1     0.26780603E-20    # coeffBB_SLRNP
 01050105 4141   00   1     0.14347885E-14    # coeffBB_VLLNP
 01050105 4242   00   1     0.69117184E-21    # coeffBB_VRRNP
 01050105 4142   00   1    -0.12080105E-20    # coeffBB_VLRNP
 01050105 4343   00   1    -0.10382757E-21    # coeffBB_TLLNP
 01050105 4444   00   1     0.13090853E-20    # coeffBB_TRRNP
 03050305 3131   00   1    -0.30211437E-20    # coeffBsBs_SLLNP
 03050305 3232   00   1     0.51558203E-18    # coeffBsBs_SRRNP
 03050305 3132   00   1    -0.65340960E-19    # coeffBsBs_SLRNP
 03050305 4141   00   1    -0.16569173E-14    # coeffBsBs_VLLNP
 03050305 4242   00   1     0.22852399E-21    # coeffBsBs_VRRNP
 03050305 4142   00   1     0.23839198E-19    # coeffBsBs_VLRNP
 03050305 4343   00   1     0.83838969E-22    # coeffBsBs_TLLNP
 03050305 4444   00   1    -0.16916574E-20    # coeffBsBs_TRRNP
 01030103 3131   00   0    -0.16120365E-23    # coeffKK_SLLSM
 01030103 3232   00   0    -0.58193459E-21    # coeffKK_SRRSM
 01030103 3132   00   0    -0.31013199E-21    # coeffKK_SLRSM
 01030103 4141   00   0     0.61821259E-14    # coeffKK_VLLSM
 01030103 4242   00   0     0.26767221E-30    # coeffKK_VRRSM
 01030103 4142   00   0    -0.30628415E-22    # coeffKK_VLRSM
 01030103 4343   00   0     0.63682199E-48    # coeffKK_TLLSM
 01030103 4444   00   0    -0.20198844E-45    # coeffKK_TRRSM
 01050105 3131   00   0    -0.88272494E-21    # coeffBB_SLLSM
 01050105 3232   00   0    -0.85820431E-15    # coeffBB_SRRSM
 01050105 3132   00   0    -0.69624408E-17    # coeffBB_SLRSM
 01050105 4141   00   0     0.30253550E-11    # coeffBB_VLLSM
 01050105 4242   00   0     0.25772468E-24    # coeffBB_VRRSM
 01050105 4142   00   0    -0.87037828E-18    # coeffBB_VLRSM
 01050105 4343   00   0    -0.19872981E-53    # coeffBB_TLLSM
 01050105 4444   00   0    -0.52096476E-48    # coeffBB_TRRSM
 03050305 3131   00   0     0.36772607E-18    # coeffBsBs_SLLSM
 03050305 3232   00   0     0.99035389E-15    # coeffBsBs_SRRSM
 03050305 3132   00   0     0.15266634E-15    # coeffBsBs_SLRSM
 03050305 4141   00   0    -0.34913285E-11    # coeffBsBs_VLLSM
 03050305 4242   00   0    -0.10737912E-21    # coeffBsBs_VRRSM
 03050305 4142   00   0     0.19083473E-16    # coeffBsBs_VLRSM
 03050305 4343   00   0     0.16958277E-50    # coeffBsBs_TLLSM
 03050305 4444   00   0     0.65120594E-48    # coeffBsBs_TRRSM
