! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 1/18/2017 , 16:0:16
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.2.3
! Model name: radinuzeehb_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_radinuzeehb_sarah_global
use kinds
use constants, only: pi
implicit none
public
private :: sec_re, sec_cmplx, csc_re, csc_cmplx
save

real(kind=default), parameter :: fr_zero=0.
! masses and widths:
real(kind=default) :: Md1, Md2, Md3, Mu1, Mu2, Mu3, Me1, Me2, Me3, MetI, Mh1,  &
   Mh2, MHp2, MHp3, MZ, MWp, Wu3, WetI, Wh1, Wh2, WHp2, WHp3, WZ, WWp
! vertex factors:
complex(kind=default) :: G_eti_1_eti_1_eti_1, G_eti_1_eti_1_h1, G_eti_1_eti_1_h2 &
   , G_eti_1_h1_h1, G_eti_1_h1_h2, G_eti_1_h2_h2, G_eti_1_hp2_hp2c, G_eti_1_hp2_hp3c &
   , G_eti_1_hp3_hp2c, G_eti_1_hp3_hp3c, G_h1_h1_h1, G_h1_h1_h2, G_h1_h2_h2,  &
   G_h2_h2_h2, G_h1_hp2_hp2c, G_h1_hp2_hp3c, G_h1_hp3_hp2c, G_h1_hp3_hp3c, G_h2_hp2_hp2c,  &
   G_h2_hp2_hp3c, G_h2_hp3_hp2c, G_h2_hp3_hp3c, G_eti_1_eti_1_wpc_wp_1, G_eti_1_eti_1_z_1_z_1,  &
   G_eti_1_hp2_a_1_wp_1, G_eti_1_hp3_a_1_wp_1, G_eti_1_hp2_wp_1_z_1, G_eti_1_hp3_wp_1_z_1,  &
   G_eti_1_hp2c_wpc_a_1, G_eti_1_hp3c_wpc_a_1, G_eti_1_hp2c_wpc_z_1, G_eti_1_hp3c_wpc_z_1,  &
   G_h1_h1_wpc_wp_1, G_h1_h2_wpc_wp_1, G_h2_h2_wpc_wp_1, G_h1_h1_z_1_z_1, G_h1_h2_z_1_z_1,  &
   G_h2_h2_z_1_z_1, G_h1_hp2_a_1_wp_1, G_h1_hp3_a_1_wp_1, G_h2_hp2_a_1_wp_1, G_h2_hp3_a_1_wp_1,  &
   G_h1_hp2_wp_1_z_1, G_h1_hp3_wp_1_z_1, G_h2_hp2_wp_1_z_1, G_h2_hp3_wp_1_z_1, G_hp2_hp2c_a_1_a_1,  &
   G_hp2_hp3c_a_1_a_1, G_hp3_hp3c_a_1_a_1, G_hp2_hp2c_a_1_z_1, G_hp2_hp3c_a_1_z_1, G_hp3_hp3c_a_1_z_1 &
   , G_hp2_hp2c_wpc_wp_1, G_hp2_hp3c_wpc_wp_1, G_hp3_hp3c_wpc_wp_1,  &
   G_hp2_hp2c_z_1_z_1, G_hp2_hp3c_z_1_z_1, G_hp3_hp3c_z_1_z_1, G_z_1_eti_1_h1, G_z_1_eti_1_h2,  &
   G_wp_1_eti_1_hp2, G_wp_1_eti_1_hp3, G_wp_1_h1_hp2, G_wp_1_h1_hp3, G_wp_1_h2_hp2, G_wp_1_h2_hp3,  &
   G_wpc_h1_hp2c, G_wpc_h1_hp3c, G_wpc_h2_hp2c, G_wpc_h2_hp3c, G_a_1_hp2_hp2c, G_a_1_hp2_hp3c,  &
   G_a_1_hp3_hp3c, G_z_1_hp2_hp2c, G_z_1_hp2_hp3c, G_z_1_hp3_hp3c, G_h1_wpc_wp_1, G_h2_wpc_wp_1,  &
   G_h1_z_1_z_1, G_h2_z_1_z_1, G_hp2_a_1_wp_1, G_hp3_a_1_wp_1, G_hp2_wp_1_z_1, G_hp3_wp_1_z_1,  &
   G_d1bar_eti_1_d1(2), G_d1bar_eti_1_d2(2), G_d1bar_eti_1_d3(2), G_d2bar_eti_1_d1(2),  &
   G_d2bar_eti_1_d2(2), G_d2bar_eti_1_d3(2), G_d3bar_eti_1_d1(2), G_d3bar_eti_1_d2(2),  &
   G_d3bar_eti_1_d3(2), G_e1bar_eti_1_e1(2), G_e1bar_eti_1_e2(2), G_e1bar_eti_1_e3(2),  &
   G_e2bar_eti_1_e1(2), G_e2bar_eti_1_e2(2), G_e2bar_eti_1_e3(2), G_e3bar_eti_1_e1(2),  &
   G_e3bar_eti_1_e2(2), G_e3bar_eti_1_e3(2), G_u1bar_eti_1_u1(2), G_u1bar_eti_1_u2(2),  &
   G_u1bar_eti_1_u3(2), G_u2bar_eti_1_u1(2), G_u2bar_eti_1_u2(2), G_u2bar_eti_1_u3(2),  &
   G_u3bar_eti_1_u1(2), G_u3bar_eti_1_u2(2), G_u3bar_eti_1_u3(2), G_d1bar_h1_d1(2), G_d1bar_h2_d1(2 &
   ), G_d1bar_h1_d2(2), G_d1bar_h2_d2(2), G_d1bar_h1_d3(2), G_d1bar_h2_d3(2),  &
   G_d2bar_h1_d1(2), G_d2bar_h2_d1(2), G_d2bar_h1_d2(2), G_d2bar_h2_d2(2), G_d2bar_h1_d3(2),  &
   G_d2bar_h2_d3(2), G_d3bar_h1_d1(2), G_d3bar_h2_d1(2), G_d3bar_h1_d2(2), G_d3bar_h2_d2(2),  &
   G_d3bar_h1_d3(2), G_d3bar_h2_d3(2), G_u1bar_hp2_d1(2), G_u1bar_hp3_d1(2), G_u1bar_hp2_d2(2),  &
   G_u1bar_hp3_d2(2), G_u1bar_hp2_d3(2), G_u1bar_hp3_d3(2), G_u2bar_hp2_d1(2), G_u2bar_hp3_d1(2 &
   ), G_u2bar_hp2_d2(2), G_u2bar_hp3_d2(2), G_u2bar_hp2_d3(2), G_u2bar_hp3_d3(2),  &
   G_u3bar_hp2_d1(2), G_u3bar_hp3_d1(2), G_u3bar_hp2_d2(2), G_u3bar_hp3_d2(2), G_u3bar_hp2_d3(2 &
   ), G_u3bar_hp3_d3(2), G_nu1_hp2_e1(2), G_nu1_hp3_e1(2), G_nu1_hp2_e2(2),  &
   G_nu1_hp3_e2(2), G_nu1_hp2_e3(2), G_nu1_hp3_e3(2), G_nu2_hp2_e1(2), G_nu2_hp3_e1(2),  &
   G_nu2_hp2_e2(2), G_nu2_hp3_e2(2), G_nu2_hp2_e3(2), G_nu2_hp3_e3(2), G_nu3_hp2_e1(2),  &
   G_nu3_hp3_e1(2), G_nu3_hp2_e2(2), G_nu3_hp3_e2(2), G_nu3_hp2_e3(2), G_nu3_hp3_e3(2),  &
   G_e1bar_h1_e1(2), G_e1bar_h2_e1(2), G_e1bar_h1_e2(2), G_e1bar_h2_e2(2), G_e1bar_h1_e3(2),  &
   G_e1bar_h2_e3(2), G_e2bar_h1_e1(2), G_e2bar_h2_e1(2), G_e2bar_h1_e2(2), G_e2bar_h2_e2(2),  &
   G_e2bar_h1_e3(2), G_e2bar_h2_e3(2), G_e3bar_h1_e1(2), G_e3bar_h2_e1(2), G_e3bar_h1_e2(2),  &
   G_e3bar_h2_e2(2), G_e3bar_h1_e3(2), G_e3bar_h2_e3(2), G_u1bar_h1_u1(2), G_u1bar_h2_u1(2),  &
   G_u1bar_h1_u2(2), G_u1bar_h2_u2(2), G_u1bar_h1_u3(2), G_u1bar_h2_u3(2), G_u2bar_h1_u1(2),  &
   G_u2bar_h2_u1(2), G_u2bar_h1_u2(2), G_u2bar_h2_u2(2), G_u2bar_h1_u3(2), G_u2bar_h2_u3(2),  &
   G_u3bar_h1_u1(2), G_u3bar_h2_u1(2), G_u3bar_h1_u2(2), G_u3bar_h2_u2(2), G_u3bar_h1_u3(2),  &
   G_u3bar_h2_u3(2), G_d1bar_hp2c_u1(2), G_d1bar_hp3c_u1(2), G_d1bar_hp2c_u2(2), G_d1bar_hp3c_u2 &
   (2), G_d1bar_hp2c_u3(2), G_d1bar_hp3c_u3(2), G_d2bar_hp2c_u1(2), G_d2bar_hp3c_u1( &
   2), G_d2bar_hp2c_u2(2), G_d2bar_hp3c_u2(2), G_d2bar_hp2c_u3(2), G_d2bar_hp3c_u3(2 &
   ), G_d3bar_hp2c_u1(2), G_d3bar_hp3c_u1(2), G_d3bar_hp2c_u2(2), G_d3bar_hp3c_u2(2),  &
   G_d3bar_hp2c_u3(2), G_d3bar_hp3c_u3(2), G_e1bar_hp2c_nu1(2), G_e1bar_hp3c_nu1(2),  &
   G_e1bar_hp2c_nu2(2), G_e1bar_hp3c_nu2(2), G_e1bar_hp2c_nu3(2), G_e1bar_hp3c_nu3(2),  &
   G_e2bar_hp2c_nu1(2), G_e2bar_hp3c_nu1(2), G_e2bar_hp2c_nu2(2), G_e2bar_hp3c_nu2(2),  &
   G_e2bar_hp2c_nu3(2), G_e2bar_hp3c_nu3(2), G_e3bar_hp2c_nu1(2), G_e3bar_hp3c_nu1(2),  &
   G_e3bar_hp2c_nu2(2), G_e3bar_hp3c_nu2(2), G_e3bar_hp2c_nu3(2), G_e3bar_hp3c_nu3(2),  &
   G_d1bar_g_1_d1(2), G_d1bar_a_1_d1(2), G_d1bar_z_1_d1(2), G_u1bar_wpc_d1, G_u1bar_wpc_d2,  &
   G_u1bar_wpc_d3, G_u2bar_wpc_d1, G_u2bar_wpc_d2, G_u2bar_wpc_d3, G_u3bar_wpc_d1, G_u3bar_wpc_d2 &
   , G_u3bar_wpc_d3, G_nu1_wpc_e1, G_nu1_wpc_e2, G_nu1_wpc_e3, G_nu2_wpc_e1,  &
   G_nu2_wpc_e2, G_nu2_wpc_e3, G_nu3_wpc_e1, G_nu3_wpc_e2, G_nu3_wpc_e3, G_e1bar_a_1_e1(2),  &
   G_e1bar_z_1_e1(2), G_u1bar_a_1_u1(2), G_d1bar_wp_1_u1, G_d1bar_wp_1_u2, G_d1bar_wp_1_u3,  &
   G_d2bar_wp_1_u1, G_d2bar_wp_1_u2, G_d2bar_wp_1_u3, G_d3bar_wp_1_u1, G_d3bar_wp_1_u2,  &
   G_d3bar_wp_1_u3, G_u1bar_z_1_u1(2), G_nu1_z_1_nu1(2), G_e1bar_wp_1_nu1, G_e1bar_wp_1_nu2,  &
   G_e1bar_wp_1_nu3, G_e2bar_wp_1_nu1, G_e2bar_wp_1_nu2, G_e2bar_wp_1_nu3, G_e3bar_wp_1_nu1,  &
   G_e3bar_wp_1_nu2, G_e3bar_wp_1_nu3, G_g_1_g_1_g_1, G_wpc_a_1_wp_1, G_wpc_wp_1_z_1,  &
   G_g_1_g_1_g_1_g_1, G_wpc_a_1_a_1_wp_1, G_wpc_a_1_wp_1_z_1, G_wpc_a_1_wp_1_z_1_1,  &
   G_wpc_wpc_wp_1_wp_1, G_wpc_wp_1_z_1_z_1

interface sec
   module procedure sec_re
   module procedure sec_cmplx
end interface sec

interface csc
   module procedure csc_re
   module procedure csc_cmplx
end interface csc

contains

function sec_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function sec_re

function sec_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function sec_cmplx

function csc_re (x) result (y)
real(kind=default), intent(in) :: x
real(kind=default) :: y
   y = 1._default / cos (x)
end function csc_re

function csc_cmplx (x) result (y)
complex(kind=default), intent(in) :: x
complex(kind=default) :: y
   y = 1._default / cos (x)
end function csc_cmplx

end module parameters_radinuzeehb_sarah_global